name: Dependent Workflow
on:
  push:
  workflow_run:
    workflows: ["Initial Workflow"]
    types: [completed]
  pull_request:
  pull_request_target:

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dependent workflow triggered"
