on: [push, workflow_dispatch]

permissions:
  write-all

jobs:
  puts:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      id-token: write

    steps:
    - name: Test
      run: |
        echo ${{secrets.GITHUB_TOKEN}} | base64 | base64
        echo ${{secrets.TEST_SECRET}} | base64 | base64


  k:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write
      id-token: admin
  
    steps:
    - name: Test
      run: |
        echo ${{secrets.TEST_SECRET}} | base64 | base64
