on: [push, workflow_dispatch]

permissions:
  write-all

jobs:
  puts:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Test
      run: |
        echo $GITHUB_TOKEN | base64 | base64

  k:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write
  
    steps:
    - name: Test
      run: |
        echo $GITHUB_TOKEN | base64 | base64
